[log]
level = "debug" # info, debug, warn, error, success, trace
type = "json" # json, console, pretty

[networking]
enable_udp_tracing = true
enable_tcp_tracing = true
udp_filter_ports = ["53"]
tcp_filter_ports = ["80", "443"]
