# [agent]
# daemonize = true
# stdout_path = "/tmp/kernelsnoop.log"
# stdeer_path = "/tmp/kernelsnoop.log"
# pid_file = "/tmp/kernelsnoop.pid"


# [notifications]
# enabled = true


[log]
level = "INFO" # info, debug, warn, error, success, trace
type = "pretty" # json, console, pretty


[syscall]
enabled = true
syscalls = ["sys_connect", "sys_execve" ]
