// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package ksnoop

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type process_monitor_bpfProcessInfo struct {
	Pid  uint32
	Uid  uint32
	Gid  uint32
	Comm [16]int8
}

// loadProcess_monitor_bpf returns the embedded CollectionSpec for process_monitor_bpf.
func loadProcess_monitor_bpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Process_monitor_bpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load process_monitor_bpf: %w", err)
	}

	return spec, err
}

// loadProcess_monitor_bpfObjects loads process_monitor_bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*process_monitor_bpfObjects
//	*process_monitor_bpfPrograms
//	*process_monitor_bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadProcess_monitor_bpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadProcess_monitor_bpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// process_monitor_bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type process_monitor_bpfSpecs struct {
	process_monitor_bpfProgramSpecs
	process_monitor_bpfMapSpecs
}

// process_monitor_bpfSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type process_monitor_bpfProgramSpecs struct {
	KprobeProcess *ebpf.ProgramSpec `ebpf:"kprobe_process"`
}

// process_monitor_bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type process_monitor_bpfMapSpecs struct {
	KprobeMap *ebpf.MapSpec `ebpf:"kprobe_map"`
}

// process_monitor_bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadProcess_monitor_bpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type process_monitor_bpfObjects struct {
	process_monitor_bpfPrograms
	process_monitor_bpfMaps
}

func (o *process_monitor_bpfObjects) Close() error {
	return _Process_monitor_bpfClose(
		&o.process_monitor_bpfPrograms,
		&o.process_monitor_bpfMaps,
	)
}

// process_monitor_bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadProcess_monitor_bpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type process_monitor_bpfMaps struct {
	KprobeMap *ebpf.Map `ebpf:"kprobe_map"`
}

func (m *process_monitor_bpfMaps) Close() error {
	return _Process_monitor_bpfClose(
		m.KprobeMap,
	)
}

// process_monitor_bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadProcess_monitor_bpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type process_monitor_bpfPrograms struct {
	KprobeProcess *ebpf.Program `ebpf:"kprobe_process"`
}

func (p *process_monitor_bpfPrograms) Close() error {
	return _Process_monitor_bpfClose(
		p.KprobeProcess,
	)
}

func _Process_monitor_bpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed process_monitor_bpf_bpfeb.o
var _Process_monitor_bpfBytes []byte
