package ksnoop

// THIS CODE MUST BE REFACTORED TO AVOID CODE DUPLICATION

import (
	"bytes"
	"context"
	"encoding/binary"
	"errors"
	"fmt"
	"os"
	"os/signal"
	"syscall"

	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/perf"
	"github.com/cilium/ebpf/rlimit"
	logger "github.com/containerscrew/devstdout/pkg"
	"github.com/containerscrew/kernelsnoop/internal/alerts"
	"github.com/containerscrew/kernelsnoop/internal/ksnoop/generates"
	"github.com/containerscrew/kernelsnoop/internal/ksnoop/utils"
	"golang.org/x/sys/unix"
)

const (
	// For /usr/bin/sh or /bin/bash
	shPath   = "/usr/lib/libreadline.so.8"
	shSymbol = "readline"
	// For /usr/bin/zsh
	zshPath   = "/usr/bin/zsh"
	zshSymbol = "zleentry"
)

func ShellReadline(ctx context.Context) {
	// Subscribe to signals for terminating the program.
	stopper := make(chan os.Signal, 1)
	signal.Notify(stopper, os.Interrupt, syscall.SIGTERM)

	// Retrieve the logger from the context
	log, _ := ctx.Value("log").(*logger.CustomLogger)

	// Allow the current process to lock memory for eBPF resources
	if err := rlimit.RemoveMemlock(); err != nil {
		log.Error(fmt.Sprintf("failed to remove memlock rlimit: %v. Consider using sudo or give necessary capabilities to the program", err))
	}

	// Load pre-compiled BPF programs and maps into the kernel
	objs := generates.ShellReadlineObjects{}
	if err := generates.LoadShellReadlineObjects(&objs, nil); err != nil {
		log.Error(fmt.Sprintf("failed to load BPF objects: %v", err))
	}
	defer objs.Close()

	// Link to Ureprobe for ZSH
	// Open an ELF binary and read its symbols.
	exZsh, err := link.OpenExecutable(zshPath)
	if err != nil {
		log.Error(fmt.Sprintf("opening executable: %s", err))
	}

	// Open a Uretprobe at the exit point of the symbol and attach
	// the pre-compiled eBPF program to it.
	upZsh, err := exZsh.Uretprobe(zshSymbol, objs.UretprobeZshReadline, nil)
	if err != nil {
		log.Error(fmt.Sprintf("creating uretprobe: %s", err))
	}
	defer upZsh.Close()

	// Link to Ureprobe for sh or bash
	// Open an ELF binary and read its symbols.
	exSh, err := link.OpenExecutable(shPath)
	if err != nil {
		log.Error(fmt.Sprintf("opening executable: %s", err))
	}

	// Open a Uretprobe at the exit point of the symbol and attach
	// the pre-compiled eBPF program to it.
	upSh, err := exSh.Uretprobe(shSymbol, objs.UretprobeShReadline, nil)
	if err != nil {
		log.Error(fmt.Sprintf("creating uretprobe: %s", err))
	}
	defer upSh.Close()

	// Initialize ring buffer
	events := objs.Events
	rd, err := perf.NewReader(events, 4096)
	if err != nil {
		log.Error(fmt.Sprintf("failed to create ringbuf reader: %v", err))
	}
	defer rd.Close()

	// Close the perf reader when the program exits.
	go func() {
		// Wait for a signal and close the perf reader,
		// which will interrupt rd.Read() and make the program exit.
		<-stopper
		log.Warning("Received signal, exiting program..")

		if err := rd.Close(); err != nil {
			log.Error("closing perf event reader: %s", err)
		}
	}()

	// Log that the program is listening for events, and the event type is shell_readline
	log.Info("listening for events.",
		logger.PrintMessage("event", "shell_readline"),
	)

	// ShellReadlineEvent is generated by bpf2go.
	var event generates.ShellReadlineEvent
	for {
		// Read the next event from the ring buffer.
		record, err := rd.Read()
		if err != nil {
			if errors.Is(err, perf.ErrClosed) {
				return
			}
			log.Error(fmt.Sprintf("Failed to read from ringbuf: %v", err))
			continue
		}

		// If the ring buffer is full, some events were lost.
		if record.LostSamples != 0 {
			log.Warning(fmt.Sprintf("perf event ring buffer full, dropped %d samples", record.LostSamples))
			continue
		}

		// Decode the raw sample into a ShellReadlineEvent struct.
		if err := binary.Read(bytes.NewReader(record.RawSample), binary.LittleEndian, &event); err != nil {
			log.Error(fmt.Sprintf("Error decoding event: %s", err))
			continue
		}

		// Check if the command line contains "nmap"
		if bytes.Contains(event.Line[:], []byte("nmap")) {
			err := alerts.SendNotification("kernelsnoop", "Nmap was executed on the system", "warning.png")
			if err != nil {
				log.Error(fmt.Sprintf("Failed to send notification: %s", err))
			}
		}

		// Log the event with the following fields
		log.Info("new shell command",
			logger.PrintMessage("pid", fmt.Sprintf("%d", event.Pid)),
			logger.PrintMessage("uid", fmt.Sprintf("%d", event.Uid)),
			logger.PrintMessage("user", utils.GetUsername(event.Uid)),
			logger.PrintMessage("shell", unix.ByteSliceToString(event.Shell[:])),
			logger.PrintMessage("command", unix.ByteSliceToString(event.Line[:])),
		)
	}
}
