// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package generates

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// LoadPermission_monitor_bpf returns the embedded CollectionSpec for Permission_monitor_bpf.
func LoadPermission_monitor_bpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Permission_monitor_bpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Permission_monitor_bpf: %w", err)
	}

	return spec, err
}

// LoadPermission_monitor_bpfObjects loads Permission_monitor_bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*Permission_monitor_bpfObjects
//	*Permission_monitor_bpfPrograms
//	*Permission_monitor_bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadPermission_monitor_bpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadPermission_monitor_bpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// Permission_monitor_bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type Permission_monitor_bpfSpecs struct {
	Permission_monitor_bpfProgramSpecs
	Permission_monitor_bpfMapSpecs
}

// Permission_monitor_bpfSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type Permission_monitor_bpfProgramSpecs struct {
	HandleSysChmod *ebpf.ProgramSpec `ebpf:"handle_sys_chmod"`
}

// Permission_monitor_bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type Permission_monitor_bpfMapSpecs struct {
	Events *ebpf.MapSpec `ebpf:"events"`
}

// Permission_monitor_bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadPermission_monitor_bpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type Permission_monitor_bpfObjects struct {
	Permission_monitor_bpfPrograms
	Permission_monitor_bpfMaps
}

func (o *Permission_monitor_bpfObjects) Close() error {
	return _Permission_monitor_bpfClose(
		&o.Permission_monitor_bpfPrograms,
		&o.Permission_monitor_bpfMaps,
	)
}

// Permission_monitor_bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadPermission_monitor_bpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type Permission_monitor_bpfMaps struct {
	Events *ebpf.Map `ebpf:"events"`
}

func (m *Permission_monitor_bpfMaps) Close() error {
	return _Permission_monitor_bpfClose(
		m.Events,
	)
}

// Permission_monitor_bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadPermission_monitor_bpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type Permission_monitor_bpfPrograms struct {
	HandleSysChmod *ebpf.Program `ebpf:"handle_sys_chmod"`
}

func (p *Permission_monitor_bpfPrograms) Close() error {
	return _Permission_monitor_bpfClose(
		p.HandleSysChmod,
	)
}

func _Permission_monitor_bpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed permission_monitor_bpf_x86_bpfel.o
var _Permission_monitor_bpfBytes []byte
