// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package ksnoop_permissions

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type test_bpfProcessInfo struct {
	Pid  uint32
	Uid  uint32
	Comm [16]int8
}

// loadTest_bpf returns the embedded CollectionSpec for test_bpf.
func loadTest_bpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Test_bpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load test_bpf: %w", err)
	}

	return spec, err
}

// loadTest_bpfObjects loads test_bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*test_bpfObjects
//	*test_bpfPrograms
//	*test_bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTest_bpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadTest_bpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// test_bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type test_bpfSpecs struct {
	test_bpfProgramSpecs
	test_bpfMapSpecs
}

// test_bpfSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type test_bpfProgramSpecs struct {
	KprobeProcess *ebpf.ProgramSpec `ebpf:"kprobe_process"`
}

// test_bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type test_bpfMapSpecs struct {
	KprobeMap *ebpf.MapSpec `ebpf:"kprobe_map"`
}

// test_bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTest_bpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type test_bpfObjects struct {
	test_bpfPrograms
	test_bpfMaps
}

func (o *test_bpfObjects) Close() error {
	return _Test_bpfClose(
		&o.test_bpfPrograms,
		&o.test_bpfMaps,
	)
}

// test_bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTest_bpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type test_bpfMaps struct {
	KprobeMap *ebpf.Map `ebpf:"kprobe_map"`
}

func (m *test_bpfMaps) Close() error {
	return _Test_bpfClose(
		m.KprobeMap,
	)
}

// test_bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTest_bpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type test_bpfPrograms struct {
	KprobeProcess *ebpf.Program `ebpf:"kprobe_process"`
}

func (p *test_bpfPrograms) Close() error {
	return _Test_bpfClose(
		p.KprobeProcess,
	)
}

func _Test_bpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed test_bpf_bpfeb.o
var _Test_bpfBytes []byte
