# compose.yaml
services:
  kernelsnoop:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    networks:
      - kernelsnoop
      - iproxy
    cap_add:
      - CAP_NET_ADMIN
      - CAP_BPF
      - CAP_PERFMON
    container_name: kernelsnoop
    environment:
      VIRUSTOTAL_API_KEY: /run/secrets/virustotal-api-key
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"

  grafana:
    image: docker.io/grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    networks:
      - kernelsnoop
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=false
      - GF_FEATURE_TOGGLES_ENABLE=accessControlOnCall lokiLogsDataplane
      - GF_INSTALL_PLUGINS=https://storage.googleapis.com/integration-artifacts/grafana-lokiexplore-app/grafana-lokiexplore-app-latest.zip;grafana-lokiexplore-app
    volumes:
      # - grafana-datasources:/etc/grafana/provisioning/datasources
      - grafana-storage:/var/lib/grafana
      - ./data-sources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./plugins.yaml:/etc/grafana/provisioning/plugins/app.yaml
      - ./dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./dashboards:/var/lib/grafana/dashboards

  loki:
      image: docker.io/grafana/loki:latest
      container_name: loki
      restart: unless-stopped
      networks:
        - kernelsnoop
      depends_on:
        - minio
      ports:
        - 3100:3100
      volumes:
        - ./loki-config.yaml:/etc/loki/loki-config.yaml
      command: -config.file=/etc/loki/loki-config.yaml

  minio:
    image: docker.io/bitnami/minio:latest
    container_name: minio
    restart: unless-stopped
    networks:
      - kernelsnoop
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - 'minio-data:/data'
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_DEFAULT_BUCKETS=loki

  promtail:
    image: grafana/promtail:latest
    restart: unless-stopped
    networks:
      - kernelsnoop
    volumes:
      - ./promtail-config.yaml:/etc/promtail/promtail-config.yaml
      - /var/lib/docker/:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: promtail
    command: -config.file=/etc/promtail/promtail-config.yaml

secrets:
  virustotal-api-key:
    file: .env/.env-virus-total-api-key

volumes:
  # loki:
  # promtail:
  #grafana-datasources:
  minio-data:
  grafana-storage:

networks:
  kernelsnoop:
    driver: bridge
    external: false
  iproxy:
    external: true
    driver: bridge
