# compose.yaml
services:
  kernelsnoop:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    cap_add:
      - CAP_NET_ADMIN
      - CAP_BPF
      - CAP_PERFMON
    container_name: kernelsnoop
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"

  grafana:
    image: docker.io/grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=false
      - GF_FEATURE_TOGGLES_ENABLE=accessControlOnCall lokiLogsDataplane
      - GF_INSTALL_PLUGINS=https://storage.googleapis.com/integration-artifacts/grafana-lokiexplore-app/grafana-lokiexplore-app-latest.zip;grafana-lokiexplore-app
    volumes:
      # - grafana-datasources:/etc/grafana/provisioning/datasources
      # - grafana-storage:/var/lib/grafana
      - ./data-sources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./plugins.yaml:/etc/grafana/provisioning/plugins/app.yaml
      - ./dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml

  loki:
      image: docker.io/grafana/loki:latest
      container_name: loki
      ports:
        - 3100:3100
      volumes:
        - ./loki-config.yaml:/etc/loki/loki-config.yaml
      command: -config.file=/etc/loki/loki-config.yaml

  promtail:
    image: grafana/promtail:latest
    volumes:
      - ./promtail-config.yaml:/etc/promtail/promtail-config.yaml
      - /var/lib/docker/:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: promtail
    command: -config.file=/etc/promtail/promtail-config.yaml

# secrets:
#   influxdb2-admin-username:
#     file: .env/.env.influxdb2-admin-username
#   influxdb2-admin-password:
#     file: .env/.env.influxdb2-admin-password
#   influxdb2-admin-token:
#     file: .env/.env.influxdb2-admin-token

volumes:
  # loki:
  # promtail:
  grafana-datasources:
  grafana-storage:
